### ISSUE TITLE
Brighter than stock inputs on a 20L5

### ISSUE THREAD

**Issue by tianfeng33** [skumlos/bkm-129x-simple#2]
I took a look the schematics and I am note sure what values or level is expected at the card pins.  I put it  on the scope and with 75 ohm termination and rgb is at 320mv to the rear pins. The video is definitely brighter than a direct input to the monitor.

**Comment by skumlos** [comment]
Yes this is also my experience on the L2 (that it is slightly brighter than expected, as there are no stock inputs to compare with) as I have to lower brightness a little. I have however not found it in any way "overbright" (if that's even a word). Since video goes into a transistor and they are "current controlled", the whole deal must be depending on the resistors after the THS7374. I tried fiddling a bit with them (I started at 33 Ohm, but that was way too bright), but much higher than 150 Ohm (I tried 200 Ohm, haven't got any in between), and I wouldn't get a picture at all. Since this board as such is completely different to the original board in regards to the video signal paths, I guess it is "expected" to vary. Any insights to changes that alleviates the brightness difference, is of course welcome :)

**Comment by skumlos** [comment]
I guess this also means the board seemingly works on L5 units, right?

**Comment by tianfeng33** [comment]
100% working on a 20L5.  I am going to swap the he 75 ohm termination on the inputs to 68 and that should drop the input to the 7374.  Let’s see what happens and I will report back.

**Comment by skumlos** [comment]
Hmm that shouldn't change much, unless you put a resistor in front also, to make a voltage divider. You'd then just be terminating with a wrong value. I think I'd try to find something like a ~160 Ohm and replace after the THS (except at R9 which should be 0). But I'll await your findings :)

**Comment by tianfeng33** [comment]
We don’t need to terminate the signal because we are amping it again.  There is already a voltage divider in the circuit with the 75 ohms impedance of the cables.  After some trial and error the best value I found was 27ohms.  Switching back and forth I can’t see a difference.  This was confirmed on both a genesis and SNES.  Give it a try and tell me what you think.

**Comment by skumlos** [comment]
Hmm, I will admit that I am no analog engineer, but as far as I know, the termination should match transmission line impedance, to avoid reflections and thus image distortion in this case. I would still prefer to fix this post-amplification. I'll try to solder up a board and see how I can change the outcome, by fiddling more with the R6/7/8.

**Comment by tianfeng33** [comment]
Sounds good. I get that impedance matching is important but the overly bright picture was much more problematic in my estimation. I scoped the output pins and the signals are very clean.  Even some consoles like the AES mess with thing by putting 68 ohms on the output of rgb. Either way,  Let me know what you figure out. I am willing to test and help out.

**Comment by skumlos** [comment]
Cool! But when you say overly bright, it was like *definitely* noticable? Because I for sure didn't see it as bad on the L2, at least not after I changed to 150 Ohm resistors after the THS7374, and I haven't heard others mention this. Maybe I should take my two L2s, original 129X in one, and then passthrough to the compatible and see how it looks. I guess that's the closest I can get to a reference, as the L2 otherwise has no RGB in.

**Comment by tianfeng33** [comment]
So I have a an extron cross point hooked up and my consoles are bypassed so they are measuring at just under 700mv on rgb. I can set the output to both the monitor and the card and switch back and forth.  In my estimation it was somewhere between 200 or 300mv too bright.  I had a previously overdriven rgb circuit measuring at 850mv and the card difference was brighter than that.

**Comment by skumlos** [comment]
This sounds somewhat familiar. The THS7374 mentions a 300mV voltage shift on the output to compensate to sync tip. That's why I put these surroundin not-mounted resistors in, because IIRC, they have something to do with this. I guess I need to dive into the datasheet to check this out.

**Comment by tianfeng33** [comment]
I was thinking that earlier but I am not sure that still is the case with ac coupling on the inputs but who knows.  Let me know what you end up trying.  Always here to help.

**Comment by skumlos** [comment]
So, I got some BNC cables so I could make a passthrough from the original BKM-129X to the compatible, and see them side by side. I have two PVM-9L2 monitors, and they're from the same age, and should have roughly the same usage. The original BKM-129X is (in my opinion) much more dull in colors than the compatible. Now I have not recapped the original card, and don't know if this would make a difference. However the compatible for sure is more bright and vibrant, and maybe a bit too oversaturated. It seems not to be a problem with brightness, more contrast, as if I turned down contrast I could make them appear very similar, albeit very dull. I thus started to fiddle with the resistors after the THS7374, and I must've made some mistake in my initial tests some time ago. At that time, I tried with 200 Ohm, but then I got no picture at all. I attributed this to that the THS7374 couldn't supply enough current to turn on the transistor, but I now retried with 270 Ohm, and it worked fine. I then started raising the resistor value and with 390 Ohm there's a picture, but it's severely degraded. I didn't have anything between 300 and 390, so I tried 300, and I guess this actually gives a bit more "natural" picture. I "feel" that I now don't have to turn the brightness down to retain a pleasant picture, so I guess this might be better. I'd like to try something in between, 330 maybe, so I'll see if I can dig some up. Anyways, that's about as far as I've gotten. Maybe you can try something alike, to see how it pleases your eyes. I will say though, I *really* feel the picture of the compatible is much prettier than the original, I guess this is maybe because it's the first time I've seen them heads on like this. Maybe this is because my original needs a recap...

I tried to make some pictures to show the difference, but its impossible with my phone. I think it does some color magic, which messes up reality bad...

**Comment by tianfeng33** [comment]
Interesting.  I am using the built in inputs for rgb and component in the 20l5 so I consider them to be the standard. I I ave lots of 330s kicking around and I will give it a try

**Comment by tianfeng33** [comment]
330 is still significantly brighter.  Is it possible this is dc offset?  When comparing black screens, I am seeing the card being much lighter.

**Comment by skumlos** [comment]
Hmm, if I start the 240p test suite, then take the 100 IRE, turn it to 0, which I guess should be black, then switch to another input, with nothing attached, I have a hard time seeing a difference (I cant, I tried in a completely dark room). But I dunno if it makes it harder to see on a 9". On the original 129X, 100 IRE looks more gray to me than 100 IRE on the compatible which really looks *white*...  Does the 20L5 have different settings per channel? On my monitor I have the knobs, but then I also have brightness and contrast in the menu. Also using the "White and RGB Screen" menu (in the test suite), black, white and colors to my eyes look really good.

**Comment by tianfeng33** [comment]
The are the same on both inputs.  I double checked to be sure.  When you switch inputs does your monitor display white text on the screen?  In the 240p test suite you can go to the colour bar page and match that White to the white on the page.  You can see a significant difference in the brightness of the whites on the input card where as the monitor inputs are a much closer match

**Comment by skumlos** [comment]
Yeah, the whites of the text and the whites of the bkm-129x match perfectly, as where the white from the compatible is much *whiter* than the original. Hmmm...

**Comment by skumlos** [comment]
Looking at the service manual, it mentions 0.6Vpp signals after the original output stages.

**Comment by skumlos** [comment]
OK, to fix this, simply put a 150 Ohm resistor from the already present 150 Ohm resistors of R6/7/8, and tie it to GND. The brightness then matches very close as far as I can see. Looks like ass, works a charm :) Use whatever close GND point you have.

**Comment by tianfeng33** [comment]
Calibrate those systems.  a proper 700mv rgb signal will look fantastic.

**Comment by skumlos** [comment]
Nono, I mean the circuit looks like ass, when smearing a THT resistor on. The picture looks fine :)

**Comment by skumlos** [comment]
Lemme hear when you try it. I can almost literally not read the OSD text anymore because they're so alike ;) I'll do a hardware revision with this in ASAP.

**Comment by tianfeng33** [comment]
![74338DD5-A88B-4F28-89BD-2B3F058121FD](https://user-images.githubusercontent.com/42009022/78193712-29be6680-7449-11ea-9676-6e61697aa9f8.jpeg) all done and looks good.  I would call that successful. I am just using 0603 so that needed a little extra solder to make sure it is connected

**Comment by skumlos** [comment]
Nice! Thanks for your help and feedback! Appreciated :)

**Comment by tianfeng33** [comment]
Now here is the question, does it even need the 7374 at all?

**Comment by skumlos** [comment]
In this simplified version with no pass-throughs, I would think no. I simply tried to take the original functionality and simplify it as much as possible, meaning it basically does what the original card does, buffering and switching but with fewer components. Mind that this board was created in like 3 hours, mostly as a proof of concept, because the real sauce lies in the MCU part. However, passthroughs were meant to be added, and thus here we are :) That's why it's open source, please feel free to fork, clone and make even simpler versions :D

**Comment by tianfeng33** [comment]
Awesome.  Well it seems to work well now and the issues is resolved. I’ll probably grab another one for my other slot later.
